# Generated by Django 6.0.6 on 2026-06-18 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(default='Web Design', max_length=100)),
                ('language', models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada')], default='Tamil', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('review_count', models.IntegerField(default=1000)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('duration_hours', models.IntegerField(default=2)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('total_lessons', models.IntegerField(default=10)),
                ('total_quizzes', models.IntegerField(default=10)),
                ('price', models.DecimalField(decimal_places=2, default=399.0, max_digits=10)),
                ('author_name', models.CharField(default='Kevin Marks', max_length=100)),
                ('author_avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(default='Introduction', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField(help_text='Stream source URI', max_length=500)),
                ('is_preview', models.BooleanField(default=False, help_text='Allows access without an active subscription')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('state_union_territory', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='GSTIN (Optional)')),
                ('payment_method', models.CharField(choices=[('Credit/Debit Card', 'Credit/Debit Card'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Mobile Wallets', 'Mobile Wallets')], default='UPI', max_length=50)),
                ('original_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number')),
                ('state', models.CharField(blank=True, default='Tamil Nadu', max_length=100)),
                ('city', models.CharField(blank=True, default='Chennai', max_length=100)),
                ('street_address', models.TextField(blank=True, default='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Course Access Controls',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
