# Generated by Django 6.0.6 on 2026-06-20 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lesson_thumbnail_lesson_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='expiry_duration_days',
            field=models.PositiveIntegerField(default=365, help_text='Duration in days for course access after enrollment'),
        ),
        migrations.AddField(
            model_name='courseaccess',
            name='enrollment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether this lesson is locked until previous lessons are completed'),
        ),
    ]
