# Generated by Django 6.0.6 on 2026-06-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course_expiry_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prevent_screenshots',
            field=models.BooleanField(default=True, help_text='Attempt to block screenshots and screen recording'),
        ),
        migrations.AddField(
            model_name='course',
            name='restrict_downloads',
            field=models.BooleanField(default=True, help_text='Disable right-click and common download methods'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Required answer if question_text is provided', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_file',
            field=models.FileField(blank=True, help_text='Optional downloadable file for this lesson', null=True, upload_to='lesson_files/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='question_text',
            field=models.TextField(blank=True, help_text='If present, student must answer this to complete the lesson', null=True),
        ),
    ]
